### ISSUE TITLE
Problemas al configurar nombre DNS

### ISSUE THREAD

**Issue by Princezhm** [pragmore/dev.ar#2]
hay un problema al hacer guardado de ciertos DNS.

en mi caso probe con varios dominios que empiezan justamente con la letra `P` y le removia el character, no fui mas a fondo con otros casos pero dejo ejemplos de prueba:

# input:
- prueba.com
- pprueba.com
- ppprueba.com

# output:
- `rueba.com`

**Comment by 4lb0** [comment]
@Princezhm  muchas gracias por el reporte, ya esta corregido
