### ISSUE TITLE
No hay boton de recuperar contraseña

### ISSUE THREAD

**Issue by Ignanavas** [pragmore/dev.ar#3]
![image](https://github.com/pragmore/dev.ar/assets/12445500/769451cf-22ef-4793-b725-57999e6d3466)

Hola, no puedo recuperar la contraseña a mi cuenta, y no me toma la que puse por defecto el dia que reserve el dominio.

![image](https://github.com/pragmore/dev.ar/assets/12445500/a4e3a78f-3625-4555-8282-1168e793a0f5)

Tengo la contraseña guardada en el gestor de google y no puedo acceder. Tampoco tengo un correo de confirmacion y tampoco tengo la opcion de restaurar contraseña.

Que se hace en estos casos? 

Muchas gracias desde ya por la atencion

**Comment by soterofur** [comment]
Hola! Estoy en la misma, necesito resetear la contraseña de mi mail porque no me la acuerdo. Como podemos hacer? Muchas gracias!

**Comment by 4lb0** [comment]
@soterofur enviame un correo a albo arroba pragmore.com por favor
