### ISSUE TITLE
Windows 10 - Chrome - Aceptación de contraseña compuesta solo por Espacios en Blanco

### ISSUE THREAD

**Issue by GonzaaLedesma** [pragmore/dev.ar#7]
El problema ocurre cuando un usuario intenta establecer una contraseña que consiste únicamente en espacios en blanco. La aplicación debería rechazar tales contraseñas porque no proporcionan una seguridad adecuada. En lugar de rechazar esta entrada, la aplicación la acepta, lo que puede llevar a problemas de seguridad.

Implementar y comunicar una política de contraseñas que requiera una combinación de letras, números y caracteres especiales, además de una longitud mínima.

Posibles Causas:
Falta de Validación de Entradas: La aplicación no tiene validaciones adecuadas para rechazar contraseñas que consisten únicamente en espacios en blanco.
Manejo Incorrecto de Espacios en Blanco: El backend puede estar tratando los espacios en blanco como caracteres válidos sin considerar su impacto en la seguridad.

**Comment by 4lb0** [comment]
No vamos a validar ningún tipo de seguridad de contraseña
